name: cend
description: cend mobile project

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  local_auth: ^1.1.10
  flutter_secure_storage: ^5.0.2

  flash: ^2.0.3+2
  getwidget: ^2.0.4

  retrofit: ^3.0.1
  json_annotation: ^4.4.0
  equatable: ^2.0.3

  flutter_bloc: ^8.0.1
  beamer: ^1.2.0

  intl_phone_field: ^3.0.1
  intl: ^0.17.0

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter


dev_dependencies:
  json_serializable: ^6.1.4
  retrofit_generator: ^4.0.1
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/logo.jpeg
